apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logintracker
  namespace: tos
  labels:
    run: logintracker
    namespace: tos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: logintracker
        namespace: tos
    spec:
      containers:
      - name: logintracker
        image: jc6482/logintracker:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 4242
        resources:
          requests:
            memory: "125Mi"
            cpu: "250m"
          limits:
            memory: "250Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: logintracker
  namespace: tos
spec:
  selector:
    run: logintracker
  ports:
    - name: ui-port
      protocol: TCP
      port: 4242
      targetPort: 4242
      nodePort: 30424
  type: NodePort
